# numpy for 2D and 3D data 
## open cv and numpy 
- RGB : cách phổ biến biểu diễn trong hình ảnh , mỗi hình ảnh được biểu diễn bởi nhiều kênh màu - đỏ , xanh , vàng . Mỗi kênh này có giá trị từ 0 - 255

## broadcasting 
- Broadcasting cho phép thực hiện các phép toán giữa các mảng có hình dạng khác nhau mà không cần tạo bản sao dữ liệu.

Quy tắc 1: Thêm kích thước 1 vào phía trước nếu cần

Quy tắc 2: Các kích thước phải bằng nhau hoặc bằng 1

Quy tắc 3: Mảng có kích thước 1 được "kéo dài" để khớp



## slicing 
- syntax : arr[dim1_slice, dim2_slice, dim3_slice, ...]

VD : Giải thích arr[:, 1, 0]
- : → Lấy TẤT CẢ phần tử ở chiều thứ nhất
- 1 → Lấy phần tử ở vị trí index 1 ở chiều thứ hai
- 0 → Lấy phần tử ở vị trí index 0 ở chiều thứ ba



In [8]:
import numpy as np 
arr = np.array([
    # === LỚP 0 ===
    [[ 0,  1,  2,  3,  4],    # Hàng 0
     [ 5,  6,  7,  8,  9],    # Hàng 1  
     [10, 11, 12, 13, 14],    # Hàng 2
     [15, 16, 17, 18, 19]],   # Hàng 3
    #  C0  C1  C2  C3  C4
    
    # === LỚP 1 ===
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29], 
     [30, 31, 32, 33, 34],
     [35, 36, 37, 38, 39]],
    
    # === LỚP 2 ===
    [[40, 41, 42, 43, 44],
     [45, 46, 47, 48, 49],
     [50, 51, 52, 53, 54],
     [55, 56, 57, 58, 59]]
])

print(arr.shape)

(3, 4, 5)


- (3 , 4 , 5) : 3 chiều , 4 hàng , 5 cột 

In [ ]:
import cv2 
import matplotlib.pyplot as plt 


# images in files
# read the image 
image = cv2.imread('image.png' ,1)
image = image[: , : ,::-1]
# 1 : có màu , 0 : trắng đen 
print(image.shape)
# ==> ouput = (width , height , depth)

# display the image 
plt.show(image , cmap = 'gray')
# sử dụng maplot sẽ bị thay đổi màu so với cv2 


## image loading 

In [ ]:
import cv2 
import matplotlib.pyplot as plt 

image = cv2.imread('image.png' , 0)
cv2.imwrite('new_image' ,image)


In [ ]:
import numpy as np
import glob # hỗ trợ đọc file trong folder 
from tqdm import tqdm # hiển thị thời gian chạy 

paths = glob.glob('samples/*.jpg').sort()
paths = sorted(paths)
# sorted tạo ra list mới và sắp xếp list đó 
# sort sắp xếp list gốc 

# read , resize and add to list 
res = []
for path in tqdm(paths) : 
    img = cv2.imread(path , 1)
    img = cv2.resize(img , (100 , 100))
    res.append(img)

res = np.array(res)
print(res.shape)

[]


### brightness changes (thay đổi độ sáng)

In [ ]:
import cv2 
import matplotlib.pyplot as plt 

img = cv2.imread('image.png' , 1)
img = img - 50 # broadcasting in numpy 
img = img[: , : , ::-1]
plt.imshow(img)

In [ ]:
import cv2 
import matplotlib.pyplot as plt 

img = cv2.imread('image.png' , 1)
print(img.dtype)

## np.clip() function 
- giới hạn các giá trị trong mảng numpy trong 1 khoảng nhất định 
- syntax : np.clip(a, a_min, a_max, out=None)
- np.clip() đảm bảo tất cả pixel đều nằm trong khoảng hợp lệ [0, 255] trước khi chuyển đổi sang uint8.


In [ ]:
# numpy.clip() 
# các số trong image được biểu diễn từ 0 - 255 và có tính chất xoay vòng 
import numpy as np 
import cv2 
import matplotlib.pyplot as plt 

img = cv2.imread('image.png' , 1)
img = img.astype(float)
print(img)

# process
img = img + 20 
img = np.clip(img , a_min = 0 , a_max = 255)

img = img[: , : ,::-1]
img = img.astype(np.uint8)
plt.imshow(img)

In [ ]:
# where function 
arr = np.arange(10)
print(arr)

out = np.where(arr < 3 , arr , arr * 2)
# nếu đúng nhận tham số 1 , nếu sai nhận tham số 2 
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  6  8 10 12 14 16 18]


In [ ]:
# numpy.clip() 
# các số trong image được biểu diễn từ 0 - 255 và có tính chất xoay vòng 
import numpy as np 
import cv2 
import matplotlib.pyplot as plt 

img = cv2.imread('image.png' , 1)
img = img.astype(float)

# process
img = img + 20 
img = np.where(img , 0 , img)

img = img[: , : ,::-1]
img = img.astype(np.uint8)
plt.show(img)

## color conversion 
- apply_along_axis() function 

In [7]:
def compute_avg(vector):
    return vector.mean()

data = np.arange(9).reshape(3 , 3)

vector = np.apply_along_axis(compute_avg , axis = 0 , arr = data)

print(vector)


[3. 4. 5.]


In [ ]:
import numpy as np 
import cv2 
import matplotlib.pyplot as plt 

def compute_avg(vector) :
    return vector.mean()

img = cv2.imread('image.png' , 1)
img = np.apply_along_axis(compute_avg , axis = 2 , arr = img)

# show 
img = img.astype(np.uint8)
plt.imshow(img , cmap = 'gray')
