# einstein summation 
- tìm chỉ mục có bên tái nhưng không có bên phải của mũi tên 
- tính tổng trên trục chỉ mục đó 
- nếu đầu ra có chỉ mục thì kết quả sẽ theo đầu ra 
- nếu đầu ra rỗng tức kết quả là 1 số 

# cách đọc einsum 
### B1 : 
- Phân tích cú pháp: np.einsum('CHỈ_SỐ->CHỈ_SỐ_ĐẦU_RA', tensor1, tensor2, ...)
### B2 : phân loại chỉ số 
1. Chỉ số TỔNG: Xuất hiện 2 lần ở đầu vào, KHÔNG có ở đầu ra
2. Chỉ số GIỮ LẠI: Xuất hiện 1 lần ở đầu vào, CÓ ở đầu ra
3. Chỉ số TỰ DO: Xuất hiện 1 lần ở đầu vào, KHÔNG có ở đầu ra (hiếm)
### B3 : quy tắc dịch 
- QUY TẮC DỊCH:
"Với mỗi [chỉ_số_giữ_lại], tính TỔNG theo [chỉ_số_tổng] của (TÍCH các phần tử)"
### B4 : dạng khai triển 
- 'ij,jk->ik'
- result[i,k] = Σⱼ (A[i,j] × B[j,k])
### B5 : xác định shape kết quả 
- Quy tắc: Shape đầu ra = tích các chiều tương ứng với chỉ số giữ lại

In [ ]:
import numpy as np 

u = np.array([3 , 2 , 4 , 1])
v = np.array([2 , 1 , 0 , 3])

r = np.einsum('i,i->' , u , v) 
# số dim phụ thuộc vào số index bên trái --> tức input là các vector 
# nếu là ma trận thì sẽ là ij 
r 

np.int64(11)

In [ ]:
# hai inputs đều là vector do chỉ có 1 chỉ mục 
# tính theo j vì có bên trái nhưng không xuất hiện bên phải 
r = np.einsum('i,j->i' , u , v)
r 
"""
    - tức tính tổng theo từ j đến n(thường là 3 vì đại diện cho dim)
    - đầu ra là chỉ mục i nên sẽ là 1 vector 
    - r[i] = Σⱼ (u[i] * v[j])
    
"""

array([18, 12, 24,  6])

In [ ]:
r = np.einsum('i,j->j' , u , v)
r 
"""
    r[j] = Σi (u[i] * v[j])
"""

array([20, 10,  0, 30])

In [ ]:
# vì đầu ra có 2 chỉ mục nên kết quả sẽ là 1 ma trận 
# vì cả 2 chỉ mục đều xuất hiện ở cả 2 vế nên sẽ không tồn tại tổng 
r = np.einsum('i,j->ij' , u , v)
r 

array([[ 6,  3,  0,  9],
       [ 4,  2,  0,  6],
       [ 8,  4,  0, 12],
       [ 2,  1,  0,  3]])

In [ ]:
# đầu ra chắc chắn là 1 ma trận 
# có sự nghịch đảo ở 2 vế nên sẽ là ma trận chuyển vị 
A = np.array([
    [0 ,2 , 1],
    [3 , 1 , 4],
])
r = np.einsum('ij->ji' , A)
r

array([[0, 3],
       [2, 1],
       [1, 4]])

In [10]:
# đầu ra là 1 vector 
# input là 1 ma trận vuông vì chỉ mục đều là i 
# lấy các phần tử trên dường chéo chính 
A = np.array([
    [0 ,2 , 1],
    [3 , 1 , 4],
    [9 , 7 , 4],
])
r = np.einsum('ii->i' , A)
r 

array([0, 1, 4])

In [ ]:
# đầu ra không có nên sẽ là tổng tính theo i 
# đây là ma trận vuông vì có 2 chỉ mục giống nhau 
# tổng = tổng theo i [Aii]
A = np.array([
    [0 ,1  , 2],
    [2 , 3 ,4],
    [6 , 7 , 8],
])

r = np.einsum('ii->', A)
r 

np.int64(11)

In [ ]:
A = np.array([
    [0 ,2 , 1],
    [3 , 1 , 4],
])
B = np.array([
    [0 ,2 , 1],
    [3 , 1 , 5],
])

r = np.einsum('ij,ij->ij' , A , B)
r
# Cij = Aij * Bij 

array([[ 0,  4,  1],
       [ 9,  1, 20]])

In [ ]:
# ouput là ma trận 
# Cik = Aij * Bik 
# tính tổng theo chỉ mục j 
r = np.einsum('ij,jk->ik' , A , B)
r 
# (5 ,) -> 5 phần tử 
# (3 , 4) -> 3 hàng , 4 cột 
# (3 , 4 , 5) -> 3 khối , mỗi khối 4 hàng 5 cột  