# vector and matrix for high - level notations 
- vector : mặc định hiểu là vector cột nếu không nói trước 
- vector addition 
- vector subtraction 
- dot product 
- matrix - matrix multiplication 
- transpose : chuyển vị (dòng -> cột , cột -> dòng)
- other hadamard operations 

In [1]:
import numpy as np    
import cv2 

data = np.array([1 , 2 , 3])
vector = np.array([1 , 1 , 1])

print(data @ vector)

6


### argmin (argument of the minimum) & argmax (argument of the maximum)


# einstein summation : tương tự tích vô hướng 
- Einstein summation (quy ước tổng Einstein) là một cách viết cực kỳ gọn gàng và mạnh mẽ để biểu diễn các phép toán trên mảng/tensor nhiều chiều. Nó loại bỏ hoàn toàn các ký hiệu tổng (Σ) và dựa vào việc lặp lại chỉ số.
- Quy tắc vàng của Einstein summation: "Khi một chỉ số xuất hiện hai lần trong một biểu thức, nó ngầm định một phép tổng theo chỉ số đó."


- Cú pháp của np.einsum: np.einsum('subscripts', operand1, operand2, ...)

- Chỉ số đầu vào: Mô tả kích thước của các toán hạng

- Chỉ số đầu ra: Mô tả kích thước kết quả (sau dấu ->)

- Quy tắc:

- Chỉ số xuất hiện một lần trong đầu vào và có trong đầu ra → giữ nguyên chiều đó

- Chỉ số xuất hiện hai lần trong đầu vào và không có trong đầu ra → tổng theo chiều đó



In [23]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Ví dụ 1: Tích vô hướng    
result = np.einsum('i,i->', a, b)
# ↑ Chỉ số 'i' xuất hiện 2 lần → tổng theo i 
# Tính: 1×4 + 2×5 + 3×6 = 4 + 10 + 18 = 32 
result 

np.int64(32)

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Ví dụ 2: Nhân ma trận
result = np.einsum('ij,jk->ik', A, B)
# ↑ 'j' xuất hiện 2 lần → tổng theo j (bị loại khỏi đầu ra)
# ↑ 'i' và 'k' chỉ xuất hiện 1 lần → được giữ lại trong đầu ra
result 

array([[19, 22],
       [43, 50]])

In [5]:
import numpy as np 

u = np.array([3 , 2 , 1  ,4])
v = np.array([2 , 1 , 0 , 3])

r = np.einsum('i, i->' ,u , v)
r 

np.int64(20)

In [6]:
r = np.einsum('i , j->i' , u , v)
r

array([18, 12,  6, 24])

In [7]:
r = np.einsum('i , j->j' ,u , v)
r 

array([20, 10,  0, 30])

In [8]:
r = np.einsum('i , j->ij' , u , v)
r 

array([[ 6,  3,  0,  9],
       [ 4,  2,  0,  6],
       [ 2,  1,  0,  3],
       [ 8,  4,  0, 12]])

In [9]:
# transpose 
A = [[0 , 2 , 1] , [3 , 1 , 4]]
r = np.einsum('ij->ji' ,A)
r 

array([[0, 3],
       [2, 1],
       [1, 4]])

In [12]:
A = np.array([
    [0 , 1 , 2], 
    [2 , 3 , 4],
    [5 , 6 , 7]
])
r = np.einsum('ii->i' , A)
r 

array([0, 3, 7])

In [13]:
r = np.einsum('ii->' , A)
r 

np.int64(10)

In [15]:
A = np.array([
    [0 , 1 , 2], 
    [2 , 3 , 4],
    [5 , 6 , 7]
])
B = np.array([
    [1 , 3 , 4], 
    [9 , 8 , 5],
    [5 , 4 , 7]
])
r = np.einsum('ij,ij->ij' , A ,B)
r
# Cij = Aij * Bij

array([[ 0,  3,  8],
       [18, 24, 20],
       [25, 24, 49]])

In [ ]:
A = np.array([
    [0 , 1 , 2], 
    [2 , 3 , 4]])
B = np.array([
    [1 , 3], 
    [9 , 8],
    [5 , 4]])
C = np.einsum('ij,jk->ik' , A , B)
C 

array([[19, 16],
       [49, 46]])