# K - means 

In [2]:
import numpy as np 

In [3]:
X = np.array([1.4 , 1.5 , 1.0 , 3.0 , 3.8 , 3.1])
X

array([1.4, 1.5, 1. , 3. , 3.8, 3.1])

In [4]:
C = X[:2]
C

array([1.4, 1.5])

In [5]:
np.abs(X - 1.4)

array([0. , 0.1, 0.4, 1.6, 2.4, 1.7])

In [6]:
np.abs(X - 1.0)

array([0.4, 0.5, 0. , 2. , 2.8, 2.1])

In [7]:
D = np.abs(X - C)

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

In [10]:
""" vì không thể thực hiện trừ đối với 2 array không cùng shape """
#data = X.reshape(6 , 1)
data = X.reshape(-1 , 1) # tự động điền số chiều vào -1 
data 

array([[1.4],
       [1.5],
       [1. ],
       [3. ],
       [3.8],
       [3.1]])

In [18]:
D = np.abs(data - C) 
D 

array([[0. , 0.1],
       [0.1, 0. ],
       [0.4, 0.5],
       [1.6, 1.5],
       [2.4, 2.3],
       [1.7, 1.6]])

In [19]:
L = np.argmin(D , axis = 1)
L 

array([0, 1, 0, 1, 1, 1])

In [21]:
X[L == 0].mean()

np.float64(1.2)

In [22]:
X[L == 1].mean() 

np.float64(2.85)

In [23]:
[X[L == i].mean() for i in range(2)]

[np.float64(1.2), np.float64(2.85)]

In [ ]:
k = 2 
# 1.randomly select centroids
print('X\n' , X)
centroids = X[:k]
print('centroids\n' , centroids)

for i in range(10) : 
    # 2.compute distance
    distance = np.abs(X.reshape(-1 ,1) -  C)
    print('distance\n' , distance)

    # 3.compute labels 
    labels = np.argmin(distance , axis = 1)
    print('labels\n' , labels)

    # 4.update centroids
    centroids_new = np.array([X[labels == i].mean() for i in range(k)])
    print(centroids_new)

    # check 
    if np.all(centroids_new == centroids): 
        break

    centroids = centroids_new  

print(centroids)

X
 [1.4 1.5 1.  3.  3.8 3.1]
centroids
 [1.4 1.5]
distance
 [[0.  0.1]
 [0.1 0. ]
 [0.4 0.5]
 [1.6 1.5]
 [2.4 2.3]
 [1.7 1.6]]
labels
 [0 1 0 1 1 1]
[1.2  2.85]
[1.2  2.85]


(3, 4, 7)