In [1]:
import numpy as np
import pandas as pd

In [ ]:
# chuẩn bị dữ liệu 
data = pd.read_csv('iris_2D.csv')
data

In [ ]:
# trích xuất nhãn 
labels = data['Label'].to_numpy()
print(labels)
print(labels.shape)

[0. 0. 0. 1. 1. 1.]
(6,)


In [ ]:
# get x
# trích xuất đặc trưng 
x_data = data[['Petal_Length', 'Petal_Width']].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]


In [ ]:
# điểm dữ liệu cần dự đoán 
x_test = np.array([3.5, 1.5]).reshape(1,2)
print(x_test)

[[3.5 1.5]]


In [ ]:
# tích khoảng cách và tìm vị trí có khoảng cách nhỏ nhất 
distances = np.abs(x_data - x_test).sum(axis=1)
print(distances)

argmin = np.argmin(distances)
print(argmin, labels[argmin])

[3.4 3.3 3.3 1.  1.3 0.3]
5 1.0
