# vector - matrix 
## vector operations 
- vector addition : phần tử > 1 thì không thực hiện được broadcasting 
- vector subtraction : 
- multiplication of vectors with scalar : 
- length of vector : 
- vector division : 
- dot product : tích vô hướng 

In [1]:
import numpy as np 
u = np.array([1 , 2 , 3 , 4])
v = np.array([5 , 6 , 7 , 8])
u + v 

array([ 6,  8, 10, 12])

In [2]:
np.add(v , u)

array([ 6,  8, 10, 12])

In [3]:
np.add(u , v)

array([ 6,  8, 10, 12])

In [4]:
np.subtract(u , v)

array([-4, -4, -4, -4])

In [6]:
np.subtract(v , u)

array([4, 4, 4, 4])

In [8]:
np.multiply(2 , u)

array([2, 4, 6, 8])

In [10]:
# size of vector 
np.linalg.norm(u)

np.float64(5.477225575051661)

In [11]:
np.divide(u , v)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
np.dot(u , v)
# u1 * v1 + u2 * v2 + ... + un * vn 

np.int64(70)

## matrix operations 
- add matrix 
- subtracion matrix
- multiply matrix 
- dot product - matrix - vector 
- dot product - matrix - matrix 
- transpose (chuyển vị) : hàng thành cột , cột thành hàng 
- determinant : định thức 

In [14]:
u = np.array([[1 , 4 , 6] , [4 , 5 , 6]])
v = np.array([[2 , 5 , 9] , [7 , 8 , 9]])
u + v 

array([[ 3,  9, 15],
       [11, 13, 15]])

In [15]:
np.add(u , v)

array([[ 3,  9, 15],
       [11, 13, 15]])

In [16]:
np.subtract(u , v)

array([[-1, -1, -3],
       [-3, -3, -3]])

In [17]:
np.multiply(u , v)

array([[ 2, 20, 54],
       [28, 40, 54]])

In [ ]:
u = np.array([[1 , 2 , 3] , [4 , 5 , 6]]) # (3 , 2)
v = np.array([7 , 8 , 9]) # (3 , 1)
u.dot(v) 

array([ 50, 122])

In [22]:
# matrix - matrix : tương tự nhân 2 ma trận 
A = np.array([[1 , 2] , [3 , 4]])
B = np.array([[1 , 2] , [3 , 4]])
A.dot(B) 
# A dot B != B dot A 

array([[ 7, 10],
       [15, 22]])

In [23]:
# determinant for matrix square 
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [24]:
"""
    x.A = B ==> x.A.A^-1 = B.A^-1 ==> x = B.A^-1
    if det(A) != 0 : invertible (khả nghịch) ==> có khả năng tìm được x 
        B = A^-1 = 1/det(A) * [[d , -b] , [-c , a]] và đan dấu 
    else : 
        A is not invertible 
"""

'\n    x.A = B ==> x.A.A^-1 = B.A^-1 ==> x = B.A^-1\n    if det(A) != 0 : invertible (khả nghịch) ==> có khả năng tìm được x \n        B = A^-1 = 1/det(A) * [[d , -b] , [-c , a]] và đan dấu \n    else : \n        A is not invertible \n'

In [27]:
# matrix khả nghịch (nghịch đảo)
np.linalg.inv(A) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# cosine similarity 
- measure the similarity between two vectors ==> góc giữa 2 vector 

In [28]:
A = np.array([1 , 2 , 3])
B = np.array([4 , 5 , 6])

In [30]:
cosine = np.dot(A , B)/(np.linalg.norm(A) * np.linalg.norm(B))
cosine 

np.float64(0.9746318461970762)

- measure the similarity between two images 

In [32]:
import numpy as np 
from PIL import Image 

image1 = Image.open('/Users/macos/AIO/module 2 /w2/THỨ 3/data/image1.jpg')
image2 = Image.open('/Users/macos/AIO/module 2 /w2/THỨ 3/data/image2.jpg')
query = Image.open('/Users/macos/AIO/module 2 /w2/THỨ 3/data/query_image.jpg')

In [ ]:
img1_data = np.array(image1)
img2_data = np.array(image2)
query_data = np.array(query)

In [40]:
img1_gray = np.sum(img1_data , axis = -1 , )/3
img2_gray = np.sum(img2_data , axis = -1 , )/3
query_gray = np.sum(query_data , axis = -1 , )/3

In [41]:
img1_flatten = img1_gray.flatten() # duỗi từ ma trận về vector 
img2_flatten = img2_gray.flatten() # duỗi từ ma trận về vector 
query_flatten = query_gray.flatten() # duỗi từ ma trận về vector 

In [42]:
def compute_consine_similary(A , B) : 
    cosine = np.dot(A , B)/(np.linalg.norm(A) * np.linalg.norm(B))
    return cosine 

In [44]:
cosine1 = compute_consine_similary(img1_flatten , img2_flatten)
cosine1

np.float64(0.8855222735151416)

In [45]:
cosine2 = compute_consine_similary(img2_flatten , query_flatten)
cosine2 

np.float64(0.8300677529901683)