1. viết class và phương thức softmax 

In [ ]:
import math 
class SoftMax : 
    def __init__(self , data): 
        self.data = data 

    def soft_max(self , data) : 
        result = 0 
        for i in range(data) : 
            TS = math.exp(data[i]) 
            for j in range(data) : 
                MS += math.exp(data[j]) 
        result = TS / MS 
        return result 

class softmax_satble() : 
    def __init__(self , data) : 
        self.data = data 

    def softmax_stable(self , data) :
        c = max(data) 
        result = 0 
        for i in range(data) : 
            TS = math.exp(data[i] - c) 
            for j in range(data) : 
                MS += math.exp(data[j] - c)
        result = TS / MS 
        return result 


In [36]:
# chữa bài 1 
# khai báo thư viện 
import torch 
import torch.nn as nn

# chuyển dữ liệu về kiểu tensor 
data = torch.Tensor([1 , 2 , 3])
softMax_function = nn.Softmax(dim = 0) # dim = 0 --> chiều dữ liệu 
output = softMax_function(data)
output 


tensor([0.0900, 0.2447, 0.6652])

In [37]:
class MySoftMax(nn.Module) : 
    def __init__(self) : 
        super().__init__() 
    
    def forward(sel , x): 
        x_exp = torch.exp(x) 
        total = x_exp.sum(0 , keepdims = True)
        return x_exp / total 

mySm = MySoftMax()
output = mySm(data) 
output 


tensor([0.0900, 0.2447, 0.6652])

In [44]:
# tránh trường hợp số quá lớn không thể biểu diễn thì ta có hàm stable soft max 
class Stable_SoftMax(nn.Module) : 
    def __init__(self) : 
        super().__init__() 

    def forward(self , x) : 
        c = torch.max(x , dim = 0) # --> tensor chiều 0 tức dạng list 1 chiều 
        x_exp = torch.exp(x - c.values)
        total = x_exp.sum(0 , keepdim = True)
        return x_exp / total 

stable_SM = Stable_SoftMax()
output = stable_SM(data) 
output 


tensor([0.0900, 0.2447, 0.6652])

2. ex2 

In [ ]:
from abc import ABC , abstractmethod 
class Ward: 
    def __init__(self , name) : 
        self.__name = name 
        self.__list = [] 

    def add_person(self , person) : 
        self.__list.append(person) 
    
    def describe(self) : 
        print(f"Name :{self.__name}")
        for p in self.__list : 
            p.describe()

    def count_doctor(self) : 
        cnt = 0 
        for p in self.__list :
            if isinstance(p , Doctor) :
                cnt += 1 
        return cnt 

    def sort_age(self) : 
        self.__list.sort(key = lambda x : x.get_yob() , reverse = True)

    def compute_age(self) : 
        sum_age = 0 
        count_teachers = 0 
        for person in self.__list : 
            if isinstance('teacher' , person) : 
                sum_age += person.get_yob() 
                count_teachers += 1 
        return sum_age / count_teachers 

class Person(ABC) : 
    def __init__(self , name , yob) : 
        self._name = name 
        self._yob = yob 
    
    def get_yob(self) : 
        return self._yob 

    @abstractmethod
    def describe(self) : 
        pass 

class Student(Person) : 
    def __init__(self , name , yob , grade) : 
        super().__init__(name , yob)
        self.__grade = grade # --> chỉ lớp Student có thể truy cập 

    def describe(self):
        print(f"Student - Name :{self._name} - YoB :{self._yob} - Grade :{self.__grade}")

class Doctor(Person) : 
    def __init__(self , name , yob , specialist) : 
        super().__init__(name , yob) 
        self.__specialist = specialist

    def describe(self) : 
        print(f"Doctor - Name :{self._name} - YoB :{self._yob} - Specialist :{self.__specialist}")

class Teacher(Person) : 
    def __init__(self , name , yob , subject) : 
        super().__init__(name , yob)
        self.__subject = subject 

    def describe(self) : 
        print(f"Teacher - Name :{self._name} - YoB :{self._yob} - Subject :{self.__subject}")
    
student1 = Student ( name = " studentA " , yob =2010 , grade = " 7 " )
student1 . describe ()
print() 
teacher1 = Teacher ( name = " teacherA " , yob =1969 , subject = " Math " )
teacher1 . describe ()
print()
doctor1 = Doctor( name = " doctorA " , yob =1945 , specialist = "Endocrinologists")
doctor1.describe() 

teacher2 = Teacher ( name = " teacherB " , yob =1995 , subject = " History " )
doctor2 = Doctor ( name = " doctorB " , yob =1975 , specialist = " Cardiologists")
ward1 = Ward ( name = " Ward1 " )
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . describe ()
ward1.count_doctor()
ward1.sort_age()
print(f"numbers of doctor :{ward1.count_doctor()}")
print(f"avarge age of teachers :{int(ward1.compute_age())}")


isinstance(object , classinfo) : kiểm tra dữ liệu của tối tượng 

3.ex3

In [ ]:
class MyStack : 
    def __init__(self , capacity) : 
        self.__capacity = capacity 
        self.__list = []

    def is_empty(self) : 
        return len(self.__list) == 0

    def is_full(self) : 
        return len(self.__list) == self.__capacity 

    def pop(self) : 
        if self.is_empty() :raise Exception("empty")
        else : return self.__list.pop() 

    def push(self , value) : 
        if self.is_full() : raise Exception("overflow")
        else : self.__list.append(value)

    def top(self) : 
        if self.is_empty() : return 'Stack is empty'
        else : return self.__list[-1]


4. ex4 

In [ ]:
class MyQueue : 
    def __init__(self , capacity) : 
        self.__capacity = capacity 
        self.__list = []

    def is_empty(self) : 
        return len(self.__list) == 0 

    def is_full(self) : 
        return len(self.__list) == self.capacity 

    def dequeue(self) : 
        if self.is_empty() : raise Exception('empty')
        return self.__list.pop(0) 

    def enqueue(self, value) :
        if self.is_full() : raise Exception('full')
        return self.__list.append(value)

    def front(self) : 
        if self.is_empty() : return 'Queue is empty' 
        else : return self.__list[0]


# khi nào sử dụng self : 
- có self -> thuộc tính đối tượng 
- không self -> biến cục bộ 
- khi truy cập attributes 
- gọi method 
- làm việc với biến toàn cục 

# khi nào không dùng : 
- biến cục bộ trong method 
- tham số của method 
- temp variable 
- 